#!/bin/bash
# Setup script for CoastSat validation framework
# This script extracts baseline data from a previous commit and validation data from current commit

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VALIDATION_DIR="$SCRIPT_DIR"
BASELINE_DIR="$VALIDATION_DIR/baseline"
VALIDATION_DATA_DIR="$VALIDATION_DIR/validation"
WORKFLOW_DIR="$VALIDATION_DIR/workflow"
ORIGINAL_DIR="$SCRIPT_DIR/../CoastSat-Original"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Setting up CoastSat Validation Framework${NC}"
echo "=============================================="

# Check if original directory exists
if [ ! -d "$ORIGINAL_DIR" ]; then
    echo -e "${RED}Error: CoastSat-Original directory not found at $ORIGINAL_DIR${NC}"
    exit 1
fi

# Function to extract data from a specific commit
extract_from_commit() {
    local commit=$1
    local target_dir=$2
    local description=$3
    
    echo -e "\n${YELLOW}Extracting $description from commit: $commit${NC}"
    
    cd "$ORIGINAL_DIR"
    
    # Check if commit exists
    if ! git rev-parse --verify "$commit" > /dev/null 2>&1; then
        echo -e "${RED}Error: Commit $commit not found${NC}"
        return 1
    fi
    
    # Get commit metadata
    local commit_hash=$(git rev-parse "$commit")
    local commit_date=$(git log -1 --format=%ci "$commit")
    local commit_date_iso=$(git log -1 --format=%cI "$commit")
    local commit_message=$(git log -1 --format=%s "$commit")
    local commit_author=$(git log -1 --format="%an <%ae>" "$commit")
    local commit_ref=$(git describe --tags --exact-match "$commit" 2>/dev/null || echo "N/A")
    local extraction_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    # Create baseline metadata file
    echo "  - Creating baseline metadata..."
    cat > "$target_dir/BASELINE_INFO.md" << EOF
# Baseline Data Information

This directory contains baseline data extracted from the CoastSat-Original repository for validation purposes.

## Source Commit Information

- **Commit Hash**: \`$commit_hash\`
- **Commit Reference**: \`$commit\`
- **Git Tag** (if applicable): $commit_ref
- **Commit Date**: $commit_date ($commit_date_iso)
- **Commit Author**: $commit_author
- **Commit Message**: $commit_message

## Extraction Information

- **Extracted On**: $extraction_date
- **Extracted By**: \`$(whoami)\` on \`$(hostname)\`
- **Sites Included**: $SITES

## Data Contents

This baseline includes:
- \`transects_extended.geojson\`: Transect geometry and statistics from the baseline commit
- \`data/{site}/\`: Site-specific data files for each validation site

## Usage

This baseline data represents the starting state before running the workflow. The workflow should process new data incrementally from this point and produce results matching the validation dataset.

## Repository Information

- **Source Repository**: \`$ORIGINAL_DIR\`
- **Repository URL**: $(git remote get-url origin 2>/dev/null || echo "N/A")

---

*This file was automatically generated by \`setup_validation.sh\`*
EOF
    echo "    ✓ BASELINE_INFO.md created"
    
    # Extract transects_extended.geojson
    echo "  - Extracting transects_extended.geojson..."
    git show "$commit:transects_extended.geojson" > "$target_dir/transects_extended.geojson" 2>/dev/null || echo "    (file not found in this commit)"
    
    # Extract data files for specified sites
    if [ -n "$SITES" ]; then
        for site in $SITES; do
            echo "  - Extracting data for site: $site..."
            mkdir -p "$target_dir/data/$site"
            
            # Extract CSV files
            for file in transect_time_series.csv transect_time_series_tidally_corrected.csv tides.csv; do
                if git show "$commit:data/$site/$file" > "$target_dir/data/$site/$file" 2>/dev/null; then
                    echo "    ✓ $file"
                fi
            done
            
            # Extract XLSX file
            if git show "$commit:data/$site/$site.xlsx" > "$target_dir/data/$site/$site.xlsx" 2>/dev/null; then
                echo "    ✓ $site.xlsx"
            fi
        done
    fi
}

# Function to copy current data
copy_current_data() {
    local target_dir=$1
    local description=$2
    
    echo -e "\n${YELLOW}Copying $description from current state${NC}"
    
    cd "$ORIGINAL_DIR"
    
    # Get current commit metadata
    local commit_hash=$(git rev-parse HEAD)
    local commit_date=$(git log -1 --format=%ci HEAD)
    local commit_date_iso=$(git log -1 --format=%cI HEAD)
    local commit_message=$(git log -1 --format=%s HEAD)
    local commit_author=$(git log -1 --format="%an <%ae>" HEAD)
    local commit_ref=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "N/A")
    local extraction_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    
    # Create validation metadata file
    echo "  - Creating validation metadata..."
    cat > "$target_dir/VALIDATION_INFO.md" << EOF
# Validation Data Information

This directory contains validation data (expected results) from the current state of the CoastSat-Original repository.

## Source Commit Information

- **Commit Hash**: \`$commit_hash\`
- **Commit Date**: $commit_date ($commit_date_iso)
- **Commit Author**: $commit_author
- **Commit Message**: $commit_message
- **Git Tag** (if applicable): $commit_ref

## Extraction Information

- **Extracted On**: $extraction_date
- **Extracted By**: \`$(whoami)\` on \`$(hostname)\`
- **Sites Included**: $SITES

## Data Contents

This validation dataset includes:
- \`transects_extended.geojson\`: Current transect geometry and statistics
- \`data/{site}/\`: Current site-specific data files for each validation site

## Usage

This validation data represents the expected results after running the workflow from the baseline state. The workflow outputs should match these files when validation is successful.

## Repository Information

- **Source Repository**: \`$ORIGINAL_DIR\`
- **Repository URL**: $(git remote get-url origin 2>/dev/null || echo "N/A")

---

*This file was automatically generated by \`setup_validation.sh\`*
EOF
    echo "    ✓ VALIDATION_INFO.md created"
    
    # Copy transects_extended.geojson
    if [ -f "transects_extended.geojson" ]; then
        echo "  - Copying transects_extended.geojson..."
        cp "transects_extended.geojson" "$target_dir/"
    fi
    
    # Copy data files for specified sites
    if [ -n "$SITES" ]; then
        for site in $SITES; do
            if [ -d "data/$site" ]; then
                echo "  - Copying data for site: $site..."
                mkdir -p "$target_dir/data/$site"
                
                # Copy CSV files
                for file in transect_time_series.csv transect_time_series_tidally_corrected.csv tides.csv; do
                    if [ -f "data/$site/$file" ]; then
                        cp "data/$site/$file" "$target_dir/data/$site/"
                        echo "    ✓ $file"
                    fi
                done
                
                # Copy XLSX file
                if [ -f "data/$site/$site.xlsx" ]; then
                    cp "data/$site/$site.xlsx" "$target_dir/data/$site/"
                    echo "    ✓ $site.xlsx"
                fi
            fi
        done
    fi
}

# Function to copy workflow code
copy_workflow() {
    echo -e "\n${YELLOW}Copying workflow code${NC}"
    
    cd "$ORIGINAL_DIR"
    
    # List of files to copy
    FILES=(
        "batch_process_NZ.py"
        "batch_process_sar.py"
        "make_xlsx.py"
        "update.sh"
        "tidal_correction.ipynb"
        "slope_estimation.ipynb"
        "linear_models.ipynb"
        "polygons.geojson"
        "shorelines.geojson"
        "transects.geojson"
        "requirements.txt"
        "SDS_slope.py"
        "smoothn.py"
        ".gitignore"
    )
    
    # Copy patch_notebooks.py if it exists in validation directory
    if [ -f "$VALIDATION_DIR/workflow/patch_notebooks.py" ]; then
        cp "$VALIDATION_DIR/workflow/patch_notebooks.py" "$WORKFLOW_DIR/"
        chmod +x "$WORKFLOW_DIR/patch_notebooks.py"
        echo "  ✓ patch_notebooks.py (from validation directory)"
    fi
    
    # Copy config.json and scripts directory if they exist
    if [ -f "$VALIDATION_DIR/config.json" ]; then
        cp "$VALIDATION_DIR/config.json" "$WORKFLOW_DIR/../config.json" 2>/dev/null || true
    fi
    if [ -d "$VALIDATION_DIR/scripts" ]; then
        cp -r "$VALIDATION_DIR/scripts" "$WORKFLOW_DIR/../" 2>/dev/null || true
    fi
    
    for file in "${FILES[@]}"; do
        if [ -f "$file" ]; then
            cp "$file" "$WORKFLOW_DIR/"
            echo "  ✓ $file"
        fi
    done
    
    # Apply validation-specific fixes to batch processing scripts
    echo -e "\n${YELLOW}Applying validation-specific fixes...${NC}"
    apply_validation_fixes
    
    # Make scripts executable
    chmod +x "$WORKFLOW_DIR"/*.sh 2>/dev/null || true
    chmod +x "$WORKFLOW_DIR"/*.py 2>/dev/null || true
}

# Function to apply validation-specific fixes to copied files
apply_validation_fixes() {
    # Fix batch_process_NZ.py: Add robust empty file handling
    if [ -f "$WORKFLOW_DIR/batch_process_NZ.py" ]; then
        python3 << FIX_NZ_EOF
import re

file_path = "$WORKFLOW_DIR/batch_process_NZ.py"
with open(file_path, 'r') as f:
    content = f.read()

# Pattern to find the simple try/except block and replace with robust version
# Look for: try:\n        df = pd.read_csv(f"data/{sitename}/transect_time_series.csv")\n        df.dates = ...
pattern = r'(    try:\s+df = pd\.read_csv\(f"data/\{sitename\}/transect_time_series\.csv"\)\s+#df\.set_index\("Unnamed: 0", inplace=True\)\s+df\.dates = pd\.to_datetime\(df\.dates\)\s+min_date = str\(df\.dates\.max\(\)\.date\(\) \+ timedelta\(days=1\)\)\s+except FileNotFoundError:\s+df = pd\.DataFrame\(\))'

replacement = '''    try:
        # Check if file exists and is not empty
        csv_file = f"data/{sitename}/transect_time_series.csv"
        if os.path.exists(csv_file) and os.path.getsize(csv_file) > 0:
            df = pd.read_csv(csv_file)
            if not df.empty and 'dates' in df.columns:
                df.dates = pd.to_datetime(df.dates)
                min_date = str(df.dates.max().date() + timedelta(days=1))
            else:
                # File exists but is empty or invalid, treat as new site
                df = pd.DataFrame()
                min_date = '1984-01-01'
        else:
            # File doesn't exist or is empty, treat as new site
            df = pd.DataFrame()
            min_date = '1984-01-01'
    except (FileNotFoundError, pd.errors.EmptyDataError, KeyError) as e:
        # File doesn't exist, is empty, or invalid - treat as new site
        df = pd.DataFrame()
        min_date = '1984-01-01''''

# Try the replacement
new_content = re.sub(pattern, replacement, content, flags=re.MULTILINE | re.DOTALL)

# If replacement didn't work, try a simpler approach - find the function and replace the try block
if new_content == content:
    # Find the process_site function and replace the try block manually
    lines = content.split('\n')
    new_lines = []
    i = 0
    while i < len(lines):
        # Look for the simple try block pattern
        if (i < len(lines) - 5 and 
            'try:' in lines[i] and 
            'df = pd.read_csv(f"data/{sitename}/transect_time_series.csv")' in lines[i+1] and
            'except FileNotFoundError:' in lines[i+4]):
            # Replace with robust version
            new_lines.append('    try:')
            new_lines.append('        # Check if file exists and is not empty')
            new_lines.append('        csv_file = f"data/{sitename}/transect_time_series.csv"')
            new_lines.append('        if os.path.exists(csv_file) and os.path.getsize(csv_file) > 0:')
            new_lines.append('            df = pd.read_csv(csv_file)')
            new_lines.append('            if not df.empty and \'dates\' in df.columns:')
            new_lines.append('                df.dates = pd.to_datetime(df.dates)')
            new_lines.append('                min_date = str(df.dates.max().date() + timedelta(days=1))')
            new_lines.append('            else:')
            new_lines.append('                # File exists but is empty or invalid, treat as new site')
            new_lines.append('                df = pd.DataFrame()')
            new_lines.append('                min_date = \'1984-01-01\'')
            new_lines.append('        else:')
            new_lines.append('            # File doesn\'t exist or is empty, treat as new site')
            new_lines.append('            df = pd.DataFrame()')
            new_lines.append('            min_date = \'1984-01-01\'')
            new_lines.append('    except (FileNotFoundError, pd.errors.EmptyDataError, KeyError) as e:')
            new_lines.append('        # File doesn\'t exist, is empty, or invalid - treat as new site')
            new_lines.append('        df = pd.DataFrame()')
            new_lines.append('        min_date = \'1984-01-01\'')
            # Skip the old lines (try, read_csv, dates, min_date, except, df = DataFrame)
            i += 6
            continue
        new_lines.append(lines[i])
        i += 1
    new_content = '\n'.join(new_lines)

with open(file_path, 'w') as f:
    f.write(new_content)
print("  ✓ Applied fixes to batch_process_NZ.py")
FIX_NZ_EOF
        echo "  ✓ batch_process_NZ.py"
    fi
    
    # Fix batch_process_sar.py: Add robust error handling for extract_shorelines
    if [ -f "$WORKFLOW_DIR/batch_process_sar.py" ]; then
        python3 << FIX_SAR_EOF
import re

file_path = "$WORKFLOW_DIR/batch_process_sar.py"
with open(file_path, 'r') as f:
    lines = f.readlines()

# Find the try block around extract_shorelines and ensure proper indentation
new_lines = []
i = 0
fixed = False
while i < len(lines):
    # Look for: try:\n    output = SDS_shoreline.extract_shorelines (wrong indentation)
    if (i < len(lines) - 1 and 
        'try:' in lines[i] and 
        'output = SDS_shoreline.extract_shorelines' in lines[i+1] and
        not lines[i+1].startswith('        ')):  # Not properly indented
        new_lines.append(lines[i])  # try:
        # Fix indentation of next line
        new_lines.append('        ' + lines[i+1].lstrip())  # output = ... (properly indented)
        i += 2
        fixed = True
        continue
    new_lines.append(lines[i])
    i += 1

if fixed:
    with open(file_path, 'w') as f:
        f.writelines(new_lines)
    print("  ✓ Applied fixes to batch_process_sar.py")
else:
    print("  ℹ batch_process_sar.py already fixed or doesn't need fixes")
FIX_SAR_EOF
        echo "  ✓ batch_process_sar.py"
    fi
    
    # Fix make_xlsx.py: Fix indentation in the transects_at_site block
    if [ -f "$WORKFLOW_DIR/make_xlsx.py" ]; then
        python3 << FIX_XLSX_EOF
import re

file_path = "$WORKFLOW_DIR/make_xlsx.py"
with open(file_path, 'r') as f:
    lines = f.readlines()

# Fix indentation for lines 88-92 (0-indexed: 87-91)
# These should be inside the if len(transects_at_site) > 0: block
new_lines = []
i = 0
fixed = False
while i < len(lines):
    # Look for the problematic pattern: if len(transects_at_site) > 0: followed by unindented code
    if (i < len(lines) - 1 and 
        'if len(transects_at_site) > 0:' in lines[i] and
        i + 1 < len(lines) and
        lines[i+1].strip().startswith('transects_at_site.to_excel') and
        not lines[i+1].startswith('        ')):  # Not properly indented
        # Fix the block
        new_lines.append(lines[i])  # if statement
        # Fix lines 88-92
        j = i + 1
        # Line 88: transects_at_site.to_excel
        if j < len(lines) and lines[j].strip().startswith('transects_at_site.to_excel'):
            new_lines.append('        ' + lines[j].lstrip())
            j += 1
        # Line 89: transect_ids = list
        if j < len(lines) and lines[j].strip().startswith('transect_ids = list'):
            new_lines.append('        ' + lines[j].lstrip())
            j += 1
        # Line 90: for transect_id in transect_ids:
        if j < len(lines) and lines[j].strip().startswith('for transect_id in transect_ids:'):
            new_lines.append('        ' + lines[j].lstrip())
            j += 1
        # Line 91: if transect_id in intersects.columns:
        if j < len(lines) and lines[j].strip().startswith('if transect_id in intersects.columns:'):
            new_lines.append('            ' + lines[j].lstrip())  # 12 spaces (inside for)
            j += 1
        # Line 92: intersects[transect_id] = ...
        if j < len(lines) and lines[j].strip().startswith('intersects[transect_id]'):
            new_lines.append('                ' + lines[j].lstrip())  # 16 spaces (inside if inside for)
            j += 1
        i = j
        fixed = True
        continue
    new_lines.append(lines[i])
    i += 1

if fixed:
    with open(file_path, 'w') as f:
        f.writelines(new_lines)
    print("  ✓ Applied fixes to make_xlsx.py")
else:
    print("  ℹ make_xlsx.py already fixed or doesn't need fixes")
FIX_XLSX_EOF
        echo "  ✓ make_xlsx.py"
    fi
}

# Load configuration
CONFIG_FILE="$VALIDATION_DIR/config.json"
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${BLUE}Loading configuration from config.json${NC}"
    # Extract values using Python (more reliable than jq)
    BASELINE_COMMIT=$(python3 -c "import json; print(json.load(open('$CONFIG_FILE')).get('baseline_commit', 'HEAD~1'))" 2>/dev/null || echo "HEAD~1")
    SITES=$(python3 -c "import json; print(' '.join(json.load(open('$CONFIG_FILE')).get('validation_sites', ['nzd0001', 'sar0001'])))" 2>/dev/null || echo "nzd0001 sar0001")
    echo "  Baseline commit: $BASELINE_COMMIT"
    echo "  Validation sites: $SITES"
else
    echo -e "${YELLOW}config.json not found, using defaults${NC}"
    BASELINE_COMMIT="HEAD~1"
    SITES="nzd0001 sar0001"
fi

# Parse arguments (override config if provided)
while [[ $# -gt 0 ]]; do
    case $1 in
        --baseline-commit)
            BASELINE_COMMIT="$2"
            echo -e "${YELLOW}Overriding baseline commit from command line: $BASELINE_COMMIT${NC}"
            shift 2
            ;;
        --sites)
            SITES="$2"
            echo -e "${YELLOW}Overriding sites from command line: $SITES${NC}"
            shift 2
            ;;
        --config)
            CONFIG_FILE="$2"
            echo -e "${YELLOW}Using config file: $CONFIG_FILE${NC}"
            shift 2
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --baseline-commit COMMIT   Git commit/tag to use as baseline (overrides config.json)"
            echo "  --sites SITES              Space-separated list of site IDs (overrides config.json)"
            echo "  --config FILE              Path to config.json file (default: ./config.json)"
            echo "  --help                     Show this help message"
            echo ""
            echo "Configuration:"
            echo "  Default configuration is loaded from config.json"
            echo "  Command-line options override config.json values"
            echo ""
            echo "Example:"
            echo "  $0 --baseline-commit HEAD~3 --sites 'nzd0001 sar0001'"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Resolve baseline commit if it's a relative reference
if [[ "$BASELINE_COMMIT" =~ ^HEAD ]]; then
    cd "$ORIGINAL_DIR"
    BASELINE_COMMIT=$(git rev-parse "$BASELINE_COMMIT" 2>/dev/null || echo "$BASELINE_COMMIT")
    echo -e "${YELLOW}Resolved baseline commit: $BASELINE_COMMIT${NC}"
fi

# Create directories
mkdir -p "$BASELINE_DIR/data"
mkdir -p "$VALIDATION_DATA_DIR/data"
mkdir -p "$WORKFLOW_DIR"

# Extract baseline data
extract_from_commit "$BASELINE_COMMIT" "$BASELINE_DIR" "baseline data"

# Copy current data as validation
copy_current_data "$VALIDATION_DATA_DIR" "validation data"

# Copy workflow code
copy_workflow

echo -e "\n${GREEN}✓ Validation setup complete!${NC}"
echo ""
echo "Baseline data: $BASELINE_DIR"
echo "Validation data: $VALIDATION_DATA_DIR"
echo "Workflow code: $WORKFLOW_DIR"
echo ""
echo "Next steps:"
echo "  1. Review the extracted data"
echo "  2. Run the workflow from baseline to generate new results"
echo "  3. Compare generated results with validation data"

